### PR TITLE
Added a video tutorial

### PR DESCRIPTION
**Pull request by Maryom**
Salam,

I just have a small question, in Datez there is no func to print the date as 2016-5-14 ?
because I wrote in the video this func:

```
func printDay(){

    theDay.text = "\(gregorianDate.components.year )-\(gregorianDate.components.month)-\(gregorianDate.components.day)"
}
```

I think it's already there in Datez but I can't find it because this is the first time I use Datez. Anyways, Datez is awesome I like it ..

### CODE REVIEW

**Comment by Mazyod** [comment]
Hello, thanks for contributing! Actually, to print dates properly, the user of the library should use `NSDateFormatter`, not Datez directly. I think it is better if you make the demo using the playground code shipped with the library.

**Comment by Maryom** [comment]
@Mazyod You are welcome. Ok I deleted the video from Youtube. I knew I'm not that good in NSDateFormatter that why I asked. Well I hope I will find a good way to do the demo .. because I already think to use the playground code but I didn't find a good way to record it .. I will rethink but I can't promise to come up with a good idea because it seems that I can't think good these days ..

**Comment by Mazyod** [comment]
@Maryom Take your time! Maybe Playground is enough for datez, since it doesn't have UI related stuff, like Appz. That is fine as well.

**Comment by Maryom** [comment]
Salam,

This is a PR just to check if you like the idea or not, it is not a PR to merge because I need to fix many things in it such as size, resolution, cut the edges and more 😅 @Mazyod I would like to do gif files for:
1) Quickly and Explicitly Access Date Components.
2) Easy and Concise Date Manipulation.
3) Convenient NSDate Operators.
Do you like the idea? shall I fix the added gif and add more gifs?
Feel free to tell me what you want.

**Comment by Mazyod** [comment]
Thanks for your continuous ideas and contributions! I have to say I think we shouldn't add too many gifs and videos, especially since the idea of Datez is to provide date and time APIs. So, most developers will want to quickly see the code instructions and APIs, and looking at too many gifs won't provide as much value.

With that said, having a **single** small gif at the top could prove valuable for giving a nice animated impression for users, and could also be used in other websites like CocoaControls.

**Comment by Maryom** [comment]
@Mazyod Your welcome. I was thinking to combine all the gifs in one gif and send it to CocoaControls. Anyways, I will rethinking :) but I'm really sorry because maybe it will take a long time to come with an idea. I will try to do it ASAP إن شاء الله

**Comment by Maryom** [comment]
@Mazyod Can I know: do you prefer the gif to be like the last one? or to be like the first one? I mean do you prefer UI gif or text coded gif? I think text coded gif will help developers: "to quickly see the code instructions and APIs"

**Comment by Maryom** [comment]
@Mazyod Just to make what I mean clear :) I would like to create like this gif:
https://github.com/eliangcs/http-prompt
Do you prefer it or do you prefer UI gif?

**Comment by Mazyod** [comment]
The http-prompt library is an interactive shell, so it makes perfect sense to have a gif like that there, but since Datez is just a Swift library, we can have something simple within playgrounds, like you did it before. Playgrounds will help show us the results in the gif.

**Comment by Maryom** [comment]
@Mazyod إن شاء الله

**Comment by Maryom** [comment]
@Mazyod Salam,
I will fix the size إن شاء الله. but the idea is ok? feel free to tell me to fix anything.

**Comment by Maryom** [comment]
Sorry I pull it by mistake! Still I need to work on it.

**Comment by Maryom** [comment]
Sorry again I don't know why it pushes my tries، I'm still trying to fix the dimensions.

**Comment by Maryom** [comment]
Ok I think the last one is ok, do you agree with me? can I send it to CocoaControls? feel free if you don't like it :)

**Comment by Mazyod** [comment]
Looks great! I just have two small points:
1. You should use a relative URL, instead of `https://github.com/Maryom/Datez/...`. You see, it shouldn't point to your repository.
2. Can you please submit a PR with less commits? This PR has 8 commits, which is too much.

**Comment by Maryom** [comment]
1. I will google it ASAP.
2. Yes I agree with you, but I don't know why it pushes them to the master I thought git push just push it to my repository, Could you please guid me? because I can't google it these days.

**Pull request closed without merging**
