### PR TITLE
Gif

### PR DESCRIPTION
**Pull request by Maryom**

### CODE REVIEW

**Comment by Mazyod** [comment]
Thanks, but can you tell me exactly what changed in the new diff? I don't see a difference

**Comment by Maryom** [comment]
You are welcome. The difference is: the new Gif without NS. Could you please tell me what do you prefer to do for the new one ?
These are some suggestions:
1. Do you want to add/remove some lines of code ?
2. Do you want to change Xcode theme ? I don't think this theme is good, because it looks like girls color.

**Comment by Mazyod** [comment]
lol, I didn't notice that, thanks. I think it looks good, the theme is nice as well.

**Comment by Maryom** [comment]
No I don't like it. I just pulled it to ask you what you want me to modify more ? but I didn't write a comment because I got busy. So please what do you want me to modify ? the new one should be a big different one.

**Comment by Maryom** [comment]
Another suggestion, LICEcap has the ability to add title to the Gif. So do you want a title ?

**Comment by Mazyod** [comment]
I think this looks fine, really

**Comment by Maryom** [comment]
Title: Breeze through Date, DateComponents, and TimeInterval with Swift!
and we can specify how long it will stay then the title will disappear.

**Comment by Maryom** [comment]
Or any another title.

**Comment by Maryom** [comment]
Or I can search and see what other people did with LICEcap maybe there are some awesome tricks.

**Comment by Maryom** [comment]
Btw I just found this:
https://subvisual.co/blog/posts/137-tutorial-deploying-elixir-applications-with-docker-and-digital-ocean/

**Comment by Maryom** [comment]
This is just a try, if you like the idea ? I will make a better one with better size, and I will speed it up in photoshop. The idea is: no need to type.

**Comment by Mazyod** [comment]
I really liked the typing, the old one honestly is great. All it needs to be a little bit smaller, that's all.

**Comment by Maryom** [comment]
Ok, I have a question if you don't mind: smaller means font size or gif size ?

**Comment by Mazyod** [comment]
gif dimensions

**Comment by Maryom** [comment]
إن شاء الله I will do it ASAP.

**Comment by Maryom** [comment]
I just remember a question if you don't mind: you want the Gif without title?

**Comment by Mazyod** [comment]
Title looks fine

**Comment by Maryom** [comment]
📆 didn't appear in the title, I tried it.
إن شاء الله I will do it ASAP.

**Comment by Maryom** [comment]
Feel free if you don't like it 👍🏼 I think I should remove the cursor.

**Comment by Mazyod** [comment]
It's perfect, thanks!!

**Comment by Maryom** [comment]
You are welcome.

**Pull request merged**
