### PR TITLE
Removed outdated gif

### PR DESCRIPTION
**Pull request by Maryom**

### CODE REVIEW

**Comment by Mazyod** [comment]
even if it's outdated, it's better than nothing

**Comment by Maryom** [comment]
Well, I wish the best for SwiftKitz, when ppl see it see updated info. But unfortunately I can't record a new gif because my trial expired :(

**Comment by Mazyod** [comment]
try this https://www.cockos.com/licecap/

**Comment by Maryom** [comment]
This is awesome. I will record a new one tomorrow إن شاء الله
Thanks.

**Pull request closed without merging**
